#!/usr/bin/env zsh
# vim: ft=zsh shiftwidth=2 tabstop=2 noexpandtab

       # _ _
  # __ _| (_) __ _ ___  ___  ___
 # / _` | | |/ _` / __|/ _ \/ __|
# | (_| | | | (_| \__ \  __/\__ \
 # \__,_|_|_|\__,_|___/\___||___/


# cd aliases
alias \.\.="cd .."              # cd up one dir
alias \.\.\.="cd ../.."         # cd up two dirs
alias \.\.\.\.="cd ../../.."     # ...   three dirs

# ls aliases
alias ls='exa -h --group-directories-first'
alias l='ls -1'         # Show files in a single column
alias l.='\ls --color=always --group-directories-first -d .??*'   # Show hidden files
alias ll='ls -l'        # Show 'long' file information
alias la='ls -A'        # Show all files
alias ld='ls -ld'       # Show info about cwd
alias lx='ls -lXB'      # Sort by extension
alias lt='ls -ltr'      # Sort by date, most recent last
alias lc='ls -ltcr'     # Sort by and show change time, most recent last
alias lu='ls -ltur'     # Sort by and show access time, most recent last

# core utilities
alias grep='grep --color=auto'
alias mv='mv -vi'
alias cp='cp -v'
alias rm='trash'
alias du='du -sh'
alias cat='bat'

# Git
alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias gs='git status'
alias gc='git commit'

# Compression
alias tbz='tar -cjvf'
alias tgz='tar -czvf'
alias txz='tar -cJvf'
alias untbz='tar -xjvf'
alias untgz='tar -xzvf'
alias untxz='tar -xJvf'

# Various {{{
alias hddtemp='hddtemp --unit=F'
alias i3help='less ~/.config/i3/config'
alias info='info --vi-keys'
alias myip='curl v4.ifconfig.co'
alias netstat="netstat -nputwc"
alias pg='ping -c 3 www.google.com'
alias restart='reboot'
alias rsync='rsync --progress'
alias sicp="racket -i -p neil/sicp -l xrepl"
#}}}



# trash-cli Trash size
alias trashsize='du -sh ~/.local/usr/share/Trash'

# CPU management
alias performance="sudo cpupower --cpu all frequency-set --governor performance"

# Emacs
alias e='emacsclient -c'
alias et='emacsclient -t'

# VIM {{{
alias vi='vim'
alias nvi='nvim'
alias nv='nvim'
alias vibash="nvim ${CONFIGDIR}/bash/bashrc"
alias vialiases="nvim ${CONFIGDIR}/shell/aliases"
alias vifunctions="nvim ${CONFIGDIR}/shell/functions"
alias vims="nvim -O"    #vim: open in verticle split
alias vimt="nvim -p"    #vim: open in tabs
#}}}

# recipe's, functions, and aliases {{{
alias vivi="nvim ${CONFIGDIR}/vim/vimrc"
alias nvivi="nvim ${CONFIGDIR}/nvim/init.vim"
alias vizsh="nvim ${CONFIGDIR}/zsh/zshrc"
alias srcfxns="source ${CONFIGDIR}/shell/functions"
alias srcaliases="source ${CONFIGDIR}/shell/aliases"
alias srczsh="source ~/.zshrc"
alias srcbash="source ~/.bashrc"
#}}}

# Arch Package Management {{{
alias pacinstall='sudo pacman -S'
alias pacupgrade='sudo pacman -Syu'
alias pacremove='sudo pacman -Rsnu'
alias pacsearch='pacman -Ss'
alias pacinfo='pacman -Qi'
alias pacclean='sudo paccache -r -k 1 -v'
alias newmirrors="sudo reflector --verbose --protocol https --score 50 --number 10 --sort rate --save /etc/pacman.d/mirrorlist && cat /etc/pacman.d/mirrorlist"
alias packages="pacman -Qqen" # Display packages explicitly installed
alias orphans="pacman -Qtdq" # Display unused packages
#alias update="newmirrors && yay -Syu"
alias pp='sudo powerpill'
alias bb='sudo bb-wrapper --aur'
# }}}

# Pasta from command line
alias sprunge="curl -F'sprunge=<-' sprunge.us"

# Tmux complains
# alias tmux="TERM=tmux-256color tmux"

# Decent initial clock
alias xclock='xclock -fg white -bg black -chime'

# Simple alias for piping text unto the X clipboard
alias clipboard='xclip -selection clip'

# Manual xflux management
alias xflux='xflux -z 37921'

# MOPAC chemistry set
alias mopac='/opt/mopac/MOPAC2012.exe'

# vim: ft=zsh
