#!/bin/bash

# get them resources {{{
xrdb -merge "$HOME/.Xresources"

# get dat modmap
xmodmap "$HOME/.Xmodmap"

# disable xset and prevent screen blanking
xset -dpms
xset s off

# disable beeping
xset b off

# sync primary, clipboard, etc.
autocutsel -fork &
autocutsel -selection PRIMARY -fork &

# set a pimpin' background
feh --bg-scale "$HOME/.dotfiles/X/background.png" &

# start pulseaudio
pulseaudio --start

# save my eyes
#redshift -v -b 1.0:0.7 -l 35.9728:-83.9422 -t 6500K:3500K & &> /dev/null
# }}}

# launch
exec bspwm
