#!/usr/bin/env bash

# Shell options
set -o vi

shellopts=(autocd checkhash checkjobs histappend \
           checkwinsize cmdhist cdspell globstar \
           extglob  lithist nocaseglob no_empty_cmd_completion \
           shift_verbose)

for opt in "${shellopts[@]}"
do
    shopt -s $opt
done

shopt -u mailwarn
shopt -u hostcomplete

# Terminal options
export TERM=xterm-256color
export CLICOLOR=1
export EDITOR=vi
export VISUAL=vi
export GREP_COLOR="36"
export LESS=-X
export HISTIGNORE=$'[ \t]*:&:[fb]g:exit'
export HISTIGNORE=$'[ \t]*:&:[fb]g:exit:ls' # ignore ls
bind '"\e[Z":menu-complete'

# Fancy colors
red='\[\e[0;31m\]'
RED='\[\e[1;31m\]'
blue='\[\e[0;34m\]'
BLUE='\[\e[1;34m\]'
cyan='\[\e[0;36m\]'
CYAN='\[\e[1;36m\]'
black='\[\e[0;30m\]'
BLACK='\[\e[1;30m\]'
green='\[\e[0;32m\]'
GREEN='\[\e[1;32m\]'
yellow='\[\e[0;33m\]'
YELLOW='\[\e[1;33m\]'
magenta='\[\e[0;35m\]'
MAGENTA='\[\e[1;35m\]'
white='\[\e[0;37m\]'
WHITE='\[\e[1;37m\]'
NC='\[\e[0m\]' # No Color

# PS1
# PS1="[\j] ${yellow}\u${NC}@${green}\h:${NC}\w\n${blue}λ${NC} "
PS1="${blue}\w${NC} ${magenta}λ${NC} "
PROMPT_DIRTRIM=4

config_dir=${HOME}/Dropbox/dotfiles
source ${config_dir}/shell/aliases
source ${config_dir}/shell/functions
source ${config_dir}/bash/dircolors.sh
source ${config_dir}/shell/dirstack.sh

[[ -f ${HOME}/.bcrc ]] &&  export BC_ENV_ARGS="$HOME/.bcrc"
[[ -f ${HOME}/.dirstack ]] && dir_stack="$( cat ${HOME}/.dirstack )"

export GPG_TTY=$(tty)¬
export XDG_CONFIG_HOME=${HOME}/.config
export XDG_CONFIG_DIRS=/etc/xdg
export XDG_DATA_HOME=${HOME}/.local/share
export XDG_DATA_DIRS=/usr/local/share/:/usr/share/
export XDG_CACHE_HOME=${HOME}/.cache
export XDG_RUNTIME_DIR=${HOME}/.local/runtime
export QT_IM_MODULE=xum
export GTK_IM_MODULE=uim
unset XMODIFIERS

colors=(red RED blue BLUE cyan CYAN black BLACK \
        green GREEN yellow YELLOW magenta MAGENTA white WHITE NC )

for color in ${colors[@]}
do
    unset $color
done

